export const AI_PROVIDER_PRESETS = {
  openai: {
    label: "OpenAI",
    protocol: "openai-compatible",
    baseUrl: "https://api.openai.com/v1",
    model: "gpt-5.2",
    note: "适合复杂规划与推理；也可改成 gpt-5-mini 等更轻模型。",
  },
  deepseek: {
    label: "DeepSeek",
    protocol: "openai-compatible",
    baseUrl: "https://api.deepseek.com",
    model: "deepseek-v4-pro",
    note: "DeepSeek 官方 OpenAI-compatible 接口。",
  },
  kimi: {
    label: "Kimi / Moonshot",
    protocol: "openai-compatible",
    baseUrl: "https://api.moonshot.ai/v1",
    model: "kimi-k2.5",
    note: "月之暗面 Kimi Open Platform，OpenAI-compatible。",
  },
  qwen: {
    label: "通义千问 / DashScope",
    protocol: "openai-compatible",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    model: "qwen-plus",
    note: "阿里云百炼/DashScope 兼容模式；国际站可改为 dashscope-intl 地址。",
  },
  glm: {
    label: "智谱 GLM",
    protocol: "openai-compatible",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    model: "glm-4.5",
    note: "智谱 BigModel OpenAI-compatible 接口。",
  },
  doubao: {
    label: "豆包 / 火山方舟",
    protocol: "openai-compatible",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    model: "",
    note: "火山方舟兼容 OpenAI 调用，模型名通常填控制台里的 endpoint/model id。",
  },
  qianfan: {
    label: "百度千帆 / 文心",
    protocol: "openai-compatible",
    baseUrl: "https://qianfan.baidubce.com/v2",
    model: "ernie-4.5-turbo-128k",
    note: "百度千帆兼容接口，模型名按控制台可用列表调整。",
  },
  gemini: {
    label: "Google Gemini",
    protocol: "openai-compatible",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    model: "gemini-2.5-flash",
    note: "使用 Gemini 的 OpenAI-compatible endpoint。",
  },
  openrouter: {
    label: "OpenRouter",
    protocol: "openai-compatible",
    baseUrl: "https://openrouter.ai/api/v1",
    model: "openai/gpt-5.2",
    note: "聚合路由，可把模型名改成 OpenRouter 控制台里的任意模型。",
  },
  siliconflow: {
    label: "SiliconFlow",
    protocol: "openai-compatible",
    baseUrl: "https://api.siliconflow.cn/v1",
    model: "Qwen/Qwen3-235B-A22B-Instruct-2507",
    note: "硅基流动 OpenAI-compatible 接口，模型名按控制台可用列表调整。",
  },
  hunyuan: {
    label: "腾讯混元",
    protocol: "openai-compatible",
    baseUrl: "https://api.hunyuan.cloud.tencent.com/v1",
    model: "hunyuan-turbos-latest",
    note: "腾讯混元 OpenAI-compatible 接口，模型名按腾讯云控制台调整。",
  },
  mistral: {
    label: "Mistral",
    protocol: "openai-compatible",
    baseUrl: "https://api.mistral.ai/v1",
    model: "mistral-large-latest",
    note: "Mistral Chat Completions 接口。",
  },
  xai: {
    label: "xAI / Grok",
    protocol: "openai-compatible",
    baseUrl: "https://api.x.ai/v1",
    model: "grok-4-latest",
    note: "xAI OpenAI-compatible 接口。",
  },
  groq: {
    label: "Groq",
    protocol: "openai-compatible",
    baseUrl: "https://api.groq.com/openai/v1",
    model: "llama-3.3-70b-versatile",
    note: "Groq OpenAI-compatible 接口，适合试用高速开源模型。",
  },
  perplexity: {
    label: "Perplexity",
    protocol: "openai-compatible",
    baseUrl: "https://api.perplexity.ai",
    model: "sonar-pro",
    note: "Perplexity Sonar 接口，适合带联网检索能力的模型。",
  },
  minimax: {
    label: "MiniMax",
    protocol: "openai-compatible",
    baseUrl: "https://api.minimax.io/v1",
    model: "MiniMax-M2.7",
    note: "MiniMax OpenAI-compatible 接口。",
  },
  mimo: {
    label: "MiMo",
    protocol: "openai-compatible",
    baseUrl: "https://api.xiaomimimo.com/v1",
    model: "mimo-v2-pro",
    note: "MiMo OpenAI-compatible 接口；如账号侧模型名不同，可直接改。",
  },
  stepfun: {
    label: "阶跃星辰 StepFun",
    protocol: "openai-compatible",
    baseUrl: "https://api.stepfun.ai/v1",
    model: "step-3.5-flash",
    note: "StepFun Chat Completions API。",
  },
  anthropic: {
    label: "Claude / Opus",
    protocol: "anthropic",
    baseUrl: "https://api.anthropic.com",
    model: "claude-opus-4-8",
    note: "使用 Anthropic Messages API。",
  },
  custom: {
    label: "自定义 OpenAI 兼容",
    protocol: "openai-compatible",
    baseUrl: "",
    model: "",
    note: "填写任何兼容 /chat/completions 的服务地址和模型名。",
  },
};

export function getAiProviderPreset(provider) {
  return AI_PROVIDER_PRESETS[provider] || AI_PROVIDER_PRESETS.custom;
}
